services:
  - type: web
    name: verifile-backend
    env: docker
    rootDir: DocsSignatureAppBE
    plan: free
    envVars:
      - key: PORT
        value: 8080
      - key: FRONTEND_URL
        value: https://your-vercel-frontend-url.vercel.app # Update this later in Render dashboard
